imu_publisher:
  ros__parameters:
    i2c_port: "/dev/i2c-1"
    i2c_addr: 0x68

sllidar_node:
  ros__parameters:
    serial_port: "/dev/ttyAMA0"
    baudrate:    460800
    frame_id:    "laser"
    scan_freq:   10.0

ultra_publisher:
  ros__parameters:
    read_interval_ms: 500
