# parameters_config.yaml

server:
  host: "0.0.0.0"   # 모든 인터페이스에서 수신
  port: 5000        # 서버 포트 번호

database:
  host: "localhost" # DB 서버 주소
  user: "your_db_user"
  password: "your_db_password"
  name: "your_db_name"

robot_settings:
  emergency_battery_threshold: 10  # (%) 배터리 임계치
